dist: trusty
sudo: false
language: php

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - pecl install -f krb5-1.1.2
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: travis_retry composer install --no-interaction

script: ./vendor/bin/phpunit

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Functional tests
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      env: KAFKA_VERSION=0.11.0.1
      before_install:
        - docker-compose up -d kafka-$KAFKA_VERSION
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
      script:
        - sleep 10 # add some arbitrary time to ensure that kafka is running fine
        - docker-compose exec kafka-$KAFKA_VERSION /opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --create --partitions 3 --replication-factor 1 --topic test
        - docker-compose run -e KAFKA_BROKERS=kafka-$KAFKA_VERSION:9092 -e KAFKA_VERSION -e KAFKA_TOPIC=test test-runner
      after_script:
        - docker-compose down

notifications:
  email:
      - swansoft_team@groups.163.com
